import type { TableRow } from "./types";

export const headers: TableRow = {
	name: "Country",
	iso_code: "ISO",
	year: "Year",
	population: "Population",
	co2: "CO2",
	co2_per_capita: "CO2 per Capita",
	cement_co2: "Cement CO2",
	cement_co2_per_capita: "Cement CO2 per Capita",
	co2_growth_abs: "CO2 Growth (Absolute)",
	co2_growth_prct: "CO2 Growth (%)",
	co2_including_luc: "CO2 (Including LUC)",
	co2_including_luc_growth_abs: "CO2 (Including LUC) Growth (Absolute)",
	co2_including_luc_growth_prct: "CO2 (Including LUC) Growth (%)",
	co2_including_luc_per_capita: "CO2 (Including LUC) per Capita",
	coal_co2: "Coal CO2",
	coal_co2_per_capita: "Coal CO2 per Capita",
	cumulative_cement_co2: "Cumulative Cement CO2",
	cumulative_co2: "Cumulative CO2",
	cumulative_co2_including_luc: "Cumulative CO2 (Including LUC)",
	cumulative_coal_co2: "Cumulative Coal CO2",
	cumulative_flaring_co2: "Cumulative Flaring CO2",
	cumulative_gas_co2: "Cumulative Gas CO2",
	cumulative_luc_co2: "Cumulative Land Use Change CO2",
	cumulative_oil_co2: "Cumulative Oil CO2",
	flaring_co2: "Flaring CO2",
	flaring_co2_per_capita: "Flaring CO2 per Capita",
	gas_co2: "Gas CO2",
	gas_co2_per_capita: "Gas CO2 per Capita",
	ghg_excluding_lucf_per_capita: "GHG Excluding LUCF per Capita",
	ghg_per_capita: "GHG per Capita",
	land_use_change_co2: "Land Use Change CO2",
	land_use_change_co2_per_capita: "Land Use Change CO2 per Capita",
	methane: "Methane",
	methane_per_capita: "Methane per Capita",
	nitrous_oxide: "Nitrous Oxide",
	nitrous_oxide_per_capita: "Nitrous Oxide per Capita",
	oil_co2: "Oil CO2",
	oil_co2_per_capita: "Oil CO2 per Capita",
	share_global_cement_co2: "Share of Global Cement CO2",
	share_global_co2: "Share of Global CO2",
	share_global_co2_including_luc: "Share of Global CO2 (Including LUC)",
	share_global_coal_co2: "Share of Global Coal CO2",
	share_global_cumulative_cement_co2: "Share of Global Cumulative Cement CO2",
	share_global_cumulative_co2: "Share of Global Cumulative CO2",
	share_global_cumulative_co2_including_luc:
		"Share of Global Cumulative CO2 (Including LUC)",
	share_global_cumulative_coal_co2: "Share of Global Cumulative Coal CO2",
	share_global_cumulative_flaring_co2: "Share of Global Cumulative Flaring CO2",
	share_global_cumulative_gas_co2: "Share of Global Cumulative Gas CO2",
	share_global_cumulative_luc_co2:
		"Share of Global Cumulative Land Use Change CO2",
	share_global_cumulative_oil_co2: "Share of Global Cumulative Oil CO2",
	share_global_flaring_co2: "Share of Global Flaring CO2",
	share_global_gas_co2: "Share of Global Gas CO2",
	share_global_luc_co2: "Share of Global Land Use Change CO2",
	share_global_oil_co2: "Share of Global Oil CO2",
	share_of_temperature_change_from_ghg: "Share of Temperature Change from GHG",
	temperature_change_from_ch4: "Temperature Change from CH4",
	temperature_change_from_co2: "Temperature Change from CO2",
	temperature_change_from_ghg: "Temperature Change from GHG",
	temperature_change_from_n2o: "Temperature Change from N2O",
	total_ghg: "Total GHG",
	total_ghg_excluding_lucf: "Total GHG Excluding LUCF",
};
